# Custom commands to link to certain servers!
# {command}: {servername}
# list top priority to least
commands:
  hub: lobby
  lobby: lobby

# Messages
command-feedback:
  no-permissions: "&cYou don't have permissions to execute this command"
  incorrect-usage: "&cIncorrect usage: %usage%"
  server:
    connecting: "&7Attempting to connect you to &f%server%"
    connected: "&7Connected you to &f%server%"
    invalid-server: "&7A server by that name could not be found"
    failure: "&7Unable to connect you to %server%"
    already-connected: "&7You are already connected to that server"

# The primary server selector gui
server-selector:
  # How many rows do we want?
  rows: 3
  # The GUI Title
  title: "Server Selector"
  # How often should we refresh the GUI (in millis)
  refresh: 30000
  # Do we want to change the items if the server they represent is not available, full or the player is already connected?
  # todo re-impl this
  dynamic-items: true
  materials:
    unavailable: STONE
    connected: DIAMOND_BLOCK
  # Items we want in the GUI
  items:
    11:
      material: RED_BED
      name: "&c&l[NEW] Bed Wars"
      lore:
        - ""
        - "&8Fight other players and"
        - "&8defend your bed, purchase"
        - "&8upgrades and be the last"
        - "&8ones standing!"
        - ""
        - "&7Click to join %server-online% other players."
        - ""
      server: bedwars
    13:
      material: PAINTING
      name: "&b&lPixel Painters"
      lore:
        - ""
        - "&8Compete in a pictionary"
        - "&8styled game, taking"
        - "&8turns to draw something"
        - "&8and guessing!"
        - ""
        - "&7Click to join %server-online% other players."
        - ""
      server: pixelpainters
    15:
      material: BOW
      name: "&a&lSkywars"
      lore:
        - ""
        - "&8Each with your own island"
        - "&8and random loot"
        - "&8get to the centre and eliminate"
        - "&8your opponents!"
        - ""
        - "&7Click to join %server-online% other players."
        - ""
      server: eu3
